Bayeux client extracted from SF service internals and improved
Overseas-Student-Living/nameko-bayeux-client pull request #1
Opened 2017-03-31 10:18 UTC by iky

Generic Bayeux Nameko extension extracted from our SF service internals

I could not keep the original SF service commits as the commits could be mixed wit internal SF library changes and also the client extension code comes from two subdirs - the actual lib and its tests.

2017-04-19 17:34 UTC, mattbennett requested changes

2017-04-19 17:34 UTC, mattbennett commented on .gitignore
> +.ropeproject
I much prefer to only list _project_ files that should be ignored here. Everything else should be ignored by  developers' [global gitignore](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore). Otherwise you end up having to update this for every possible developer tool.

2017-04-19 17:34 UTC, mattbennett commented on nameko_bayeux_client/channels.py
> +    The API consists of two main methods - compose and handle.
This is somewhat redundant information

2017-04-19 17:34 UTC, mattbennett commented on nameko_bayeux_client/channels.py
> +        by a separate worker.
worth clarifying that this means a _nameko_ worker? Otherwise it could be confused with the snippets from the spec used in the other docstrings

2017-04-19 17:34 UTC, mattbennett commented on nameko_bayeux_client/client.py
> +        args = (self.channel_name, message)
Learning from https://github.com/nameko/nameko/issues/428, does it matter if the worker pool blocks here?

Might be worth adding a test-case to find out.

2017-04-19 17:34 UTC, mattbennett commented on tests/test_channels.py
> +            channel.compose()
yoda conditions?

2017-04-19 17:34 UTC, mattbennett commented on tests/test_channels.py
> +            channel.compose()
It's also nicer when debugging to have access to the expected result as a variable, so you can more easily compare individual fields.

2017-04-19 17:34 UTC, mattbennett commented on tests/test_client.py
> +def cometd_server_port():
Nameko has a `find_free_port` helper that you could use instead of this.

2017-04-19 17:34 UTC, mattbennett commented on tests/test_client.py
> +                    json.dumps([message_maker.make_connect_response()]))
There's got to be a better way to indent this! 😜

2017-04-19 17:34 UTC, mattbennett commented on tests/test_client.py
> +        responses.extend(extra_responses)
Not sure I love mutating the argument like this. Is there another way to add responses?

2017-04-19 17:34 UTC, mattbennett commented on tests/test_client.py
> +def test_handlers_do_not_block(
even when max_workers is exceeded?

2017-04-19 17:34 UTC, mattbennett commented on tests/test_client.py
> +            {'json': terminating_callback},
Where does `terminating_callback ` get invoked?

2017-04-19 17:34 UTC, mattbennett commented on tests/test_client.py
> +    ):
It's not clear to me what this is testing. Maybe add a docstring?

2017-04-19 17:46 UTC, iky commented on .gitignore
> +.ropeproject
The .gitignore is taken from [github/gitignore](https://github.com/github/gitignore/blob/master/Python.gitignore) but I agree with you, I should make it thinner .) exactly for the reasons you mensioned.

2017-04-20 16:40 UTC, iky commented on nameko_bayeux_client/channels.py
> +    The API consists of two main methods - compose and handle.
True, removed

2017-04-20 16:40 UTC, iky commented on nameko_bayeux_client/channels.py
> +        by a separate worker.
True, it's the Nameko worker, I added some clarification.

Which snippet did you mean?

2017-04-20 16:40 UTC, iky commented on tests/test_channels.py
> +            channel.compose()
yoda eliminated, :) assertion pairs swapped

also, expected message var used

2017-04-20 16:40 UTC, iky commented on nameko_bayeux_client/client.py
> +        args = (self.channel_name, message)
Yo, worth trying. I can add a test simulating blocking by worker pool limit - having more messages coming than workers available - if that is what you mean?. Here it should be OK given the fact that this implements a simple stateless HTTP long polling mechanism.

2017-04-20 16:40 UTC, iky commented on tests/test_client.py
> +def cometd_server_port():
Good to know! Thanks .)

2017-04-20 16:40 UTC, iky commented on tests/test_client.py
> +                    json.dumps([message_maker.make_connect_response()]))
;) I made it better

2017-04-20 16:40 UTC, iky commented on tests/test_client.py
> +        responses.extend(extra_responses)
The other way would be to make the fixture using it a callable and pass the responses around.

This approach is quite similar to our use of `db_session` where the "side effect" is taken even further and the data are adjusted along the way by other fixtures multiple times.

2017-04-20 16:40 UTC, iky commented on tests/test_client.py
> +        responses.extend(extra_responses)
I made the `cometd_server` a `make_cometd_server` fixture and passing the responses. It looks much better .)
Thanks! .)

2017-04-20 16:40 UTC, iky commented on tests/test_client.py
> +            {'json': terminating_callback},
The `requests_mock` accepts a callable. When the tested request/response pairs are drained, the added terminating callback will be executed by the `requests_mock` mechanism.

2017-04-20 16:40 UTC, iky commented on tests/test_client.py
> +    ):
The test class comment ^^ explains it.)

2017-04-20 16:40 UTC, iky commented on .gitignore
> +.ropeproject
I reduced the .gitignore to only items so far existing in the project

2017-04-21 17:13 UTC, mattbennett approved these changes
Great stuff!

2017-04-21 17:16 UTC, merged